ASSET_IFC_GROUPS = {
    "IfcDistributionElement",
    "IfcTransportElement",
}

ASSET_IFC_CLASSES = {
    "IfcAirTerminal",
    "IfcAirTerminalBox",
    "IfcAlarm",
    "IfcBoiler",
    "IfcChiller",
    "IfcCoolingTower",
    "IfcElectricDistributionBoard",
    "IfcFan",
    "IfcFilter",
    "IfcFlowMeter",
    "IfcHeatExchanger",
    "IfcLightFixture",
    "IfcPump",
    "IfcSensor",
    "IfcSwitchingDevice",
    "IfcTank",
    "IfcTransformer",
    "IfcTransportElement",
    "IfcUnitaryEquipment",
    "IfcValve",
}

ASSET_PROPERTY_SIGNALS = {
    "Asset Code",
    "AssetIdentifier",
    "AssetTag",
    "BarCode",
    "DT.Common.Asset Code",
    "DT.Common.Asset Tag No.",
    "DT.Common.Equipment Description",
    "DT.Common.Manufacturer",
    "DT.Common.Model No.",
    "DT.HVAC.Equipment Type",
    "InstallationDate",
    "Manufacturer",
    "ModelReference",
    "SerialNumber",
    "WarrantyEndDate",
    "WarrantyStartDate",
}

SERVICEABLE_IFC_CLASSES = {
    "IfcAirTerminal",
    "IfcAirTerminalBox",
    "IfcBoiler",
    "IfcChiller",
    "IfcCoolingTower",
    "IfcElectricDistributionBoard",
    "IfcFan",
    "IfcFilter",
    "IfcFlowMeter",
    "IfcHeatExchanger",
    "IfcLightFixture",
    "IfcPump",
    "IfcSensor",
    "IfcSwitchingDevice",
    "IfcTank",
    "IfcTransformer",
    "IfcUnitaryEquipment",
    "IfcValve",
}

SYSTEM_REQUIRED_IFC_CLASSES = {
    "IfcAirTerminal",
    "IfcAirTerminalBox",
    "IfcBoiler",
    "IfcChiller",
    "IfcCoolingTower",
    "IfcElectricDistributionBoard",
    "IfcFan",
    "IfcFilter",
    "IfcFlowMeter",
    "IfcHeatExchanger",
    "IfcLightFixture",
    "IfcPump",
    "IfcSensor",
    "IfcSwitchingDevice",
    "IfcTank",
    "IfcTransformer",
    "IfcUnitaryEquipment",
    "IfcValve",
}

DIGITAL_TWIN_ASSET_TYPE_BY_IFC_CLASS = {
    "IfcAirTerminal": "Air Terminal",
    "IfcAirTerminalBox": "Air Terminal Box",
    "IfcAlarm": "Alarm",
    "IfcBoiler": "Boiler",
    "IfcChiller": "Chiller",
    "IfcCoolingTower": "Cooling Tower",
    "IfcElectricDistributionBoard": "Electrical Distribution Board",
    "IfcFan": "Fan",
    "IfcFilter": "Filter",
    "IfcFlowMeter": "Flow Meter",
    "IfcHeatExchanger": "Heat Exchanger",
    "IfcLightFixture": "Light Fixture",
    "IfcPump": "Pump",
    "IfcSensor": "Sensor",
    "IfcSwitchingDevice": "Switching Device",
    "IfcTank": "Tank",
    "IfcTransformer": "Transformer",
    "IfcTransportElement": "Transport Element",
    "IfcUnitaryEquipment": "Unitary Equipment",
    "IfcValve": "Valve",
}

DIGITAL_TWIN_SYSTEM_BY_IFC_CLASS = {
    "IfcAirTerminal": "HVAC",
    "IfcAirTerminalBox": "HVAC",
    "IfcAlarm": "FF",
    "IfcBoiler": "HVAC",
    "IfcChiller": "HVAC",
    "IfcCoolingTower": "HVAC",
    "IfcElectricDistributionBoard": "EL",
    "IfcFan": "HVAC",
    "IfcFilter": "HVAC",
    "IfcFlowMeter": "PLB",
    "IfcHeatExchanger": "HVAC",
    "IfcLightFixture": "EL",
    "IfcPump": "HVAC",
    "IfcSensor": "BMS",
    "IfcSwitchingDevice": "EL",
    "IfcTank": "PLB",
    "IfcTransformer": "EL",
    "IfcTransportElement": "LIFT",
    "IfcUnitaryEquipment": "HVAC",
    "IfcValve": "PLB",
}

DIGITAL_TWIN_SYSTEM_KEYWORDS = {
    "ARCH": ("arch", "architect", "door", "window", "wall"),
    "BMS": ("automation", "bms", "control", "controller", "sensor"),
    "EL": ("el", "electric", "electrical", "lighting", "panel", "power", "switch"),
    "FF": ("ff", "fire", "fire fighting", "firefighting", "pccc", "sprinkler"),
    "HVAC": (
        "ahu",
        "air",
        "chw",
        "chilled",
        "duct",
        "fan",
        "hvac",
        "mechanical",
        "return",
        "supply",
        "ventilation",
    ),
    "LIFT": ("elevator", "lift", "transport"),
    "PLB": ("drain", "drainage", "pipe", "plb", "plumbing", "sanitary", "water"),
    "SEC": ("access", "camera", "cctv", "sec", "security"),
    "STR": ("beam", "column", "plate", "slab", "struct", "structure"),
}

DIGITAL_TWIN_STATUS_VALUES = {
    "active",
    "inactive",
    "maintenance",
    "planned",
    "retired",
}

DIGITAL_TWIN_STATUS_ALIASES = {
    "active": "active",
    "as built": "active",
    "asbuilt": "active",
    "commissioned": "active",
    "existing": "active",
    "in service": "active",
    "inservice": "active",
    "installed": "active",
    "new construction": "active",
    "operational": "active",
    "inactive": "inactive",
    "not in service": "inactive",
    "out of service": "inactive",
    "repair": "maintenance",
    "in maintenance": "maintenance",
    "maintenance": "maintenance",
    "under maintenance": "maintenance",
    "design": "planned",
    "future": "planned",
    "new": "planned",
    "planned": "planned",
    "planned construction": "planned",
    "proposed": "planned",
    "decommissioned": "retired",
    "demolished": "retired",
    "demolition": "retired",
    "demo": "retired",
    "removed": "retired",
    "retired": "retired",
    "to be demolished": "retired",
}

PLACEHOLDER_VALUES = {
    "-",
    "--",
    "0",
    "default",
    "generic",
    "generic manufacturer",
    "model-placeholder",
    "na",
    "n/a",
    "not applicable",
    "not available",
    "not set",
    "none",
    "null",
    "pending",
    "placeholder",
    "tbd",
    "to be checked",
    "to check",
    "unknown",
    "undefined",
}

SKIP_IFC_CLASSES = {
    "IfcAnnotation",
    "IfcOpeningElement",
    "IfcVirtualElement",
}
